# Generated by Django 5.0.3 on 2024-03-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdetails',
            table='Userinfo',
        ),
    ]
