# Generated by Django 5.0.3 on 2024-03-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_userdetails_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactdetails',
            fields=[
                ('si_no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'User_Contact_details',
            },
        ),
    ]
